### ISSUE TITLE
Verbose flag does not work for pool size > 1

### ISSUE THREAD

**Issue by HudgeW** [jacksonpradolima/coleman4hcs#60]
I noticed that setting the verbose flag in the config.toml file does not produce the intended logs in the terminal. After some research I can see that the issue is due to the use of the multiprocessing module. Logging works properly when running main with a single process. Every newly created process has it's own root logger so there becomes a problem to synch the loggers. 

I am on windows with python 3.11.5.

**Comment by jacksonpradolima** [comment]
Thanks, merged
