### ISSUE TITLE
Running with a single process produces duplicated results

### ISSUE THREAD

**Issue by HudgeW** [jacksonpradolima/coleman4hcs#61]
After simulation when we write data to the results/experiments directory there is a bug when using a single process that duplicates dataframes and writes exponentially many rows to number of experiments configured. This is because the monitor object is reused for every experiment and it's dataframe is not cleared between experiments. When using multiple processes this is not an issue since for every initiated process a new monitor object is created - I think.
![Screenshot 2024-09-23 144147](https://github.com/user-attachments/assets/82ef408c-6a1f-46d7-a3c8-54275ef667ba)

**Comment by jacksonpradolima** [comment]
Thanks, merged
